import os
import json
from pymongo import MongoClient
from dotenv import load_dotenv

def get_db():
    load_dotenv()
    uri = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
    client = MongoClient(uri)
    return client["stock_market_db"]

def main():
    db = get_db()
    result = {}
    
    # 1. RUN IDENTITY
    # Get the latest SUCCESS run for market_date or target_date = 2026-09-01
    # Check both market_date and target_date fields just in case
    run = db["pipeline_runs"].find_one(
        {"$or": [{"target_date": "2026-09-01"}, {"market_date": "2026-09-01"}], "status": "SUCCESS"},
        sort=[("started_at", -1)]
    )
    if not run:
        print("No SUCCESS run found for 2026-09-01!")
        
        # Let's see what SUCCESS runs exist
        print("Latest SUCCESS runs:")
        for r in db["pipeline_runs"].find({"status": "SUCCESS"}).sort("started_at", -1).limit(5):
            print(r.get("market_date"), r.get("target_date"), r.get("started_at"))
        
        return
        
    result["Run"] = {
        "id": str(run["_id"]),
        "run_id": run.get("run_id"),
        "market_date": run.get("market_date"),
        "target_date": run.get("target_date"),
        "started_at": str(run.get("started_at")),
        "completed_at": str(run.get("completed_at")),
        "status": run.get("status"),
        "stages": {}
    }
    for k, v in run.get("stages", {}).items():
        result["Run"]["stages"][k] = {
            "status": v.get("status"),
            "metrics": v.get("metrics")
        }
        
    # Historical Data Coverage for 2026-08-29, 2026-08-31, 2026-09-01
    dates = ["2026-08-28", "2026-08-29", "2026-08-31", "2026-09-01"]
    result["Historical"] = {}
    for d in dates:
        count = db["historical_data"].count_documents({"date": d})
        nifty_count = db["historical_data"].count_documents({"date": d, "ticker": "^NSEI"})
        result["Historical"][d] = {"count": count, "nifty_count": nifty_count}
        
    # Predictions
    # Look for predictions targeting 2026-09-01 or generated on 2026-09-01
    # We will look for target_date matching the next date or execution date.
    # Usually, if execution is 2026-09-01, target date might be 2026-09-02 (next trading session).
    # Let's find predictions generated by this run_id
    preds = list(db["prediction_history"].find({"run_id": run.get("run_id")}))
    result["Predictions"] = {
        "count": len(preds),
        "target_dates": list(set(p.get("target_date") for p in preds)),
        "tickers": len(set(p.get("ticker") for p in preds)),
    }
    
    # Feature readiness from the predictions
    nan_features = 0
    for p in preds:
        features = p.get("features", {})
        if features.get("nifty_return") is None or features.get("outperformance") is None or features.get("market_regime") is None:
            nan_features += 1
    result["Predictions"]["nan_features"] = nan_features
    
    # Provenance
    provs = list(db["prediction_provenance"].find({"run_id": run.get("run_id")}))
    result["Provenance"] = {
        "count": len(provs),
        "hashes": list(set(p.get("pipeline_hash") for p in provs))
    }
    
    # Old predictions
    # check 2026-08-31 cohort
    old_preds = list(db["prediction_history"].find({"target_date": "2026-08-31"}))
    result["Old_Predictions_2026-08-31"] = {
        "count": len(old_preds),
        "run_ids": list(set(p.get("run_id") for p in old_preds))
    }
    
    # Check old provenance
    old_provs = list(db["prediction_provenance"].find({"target_date": "2026-08-31"}))
    result["Old_Provenance_2026-08-31"] = {
        "count": len(old_provs),
        "hashes": list(set(p.get("pipeline_hash") for p in old_provs))
    }
    
    # Governance / Model Registry
    active_models = list(db["model_registry"].find({"status": "ACTIVE"}))
    result["Model_Registry"] = {
        "active_count": len(active_models),
        "hashes": list(set(m.get("pipeline_hash") for m in active_models))
    }

    with open("scratch/db_audit.json", "w") as f:
        json.dump(result, f, indent=2)

if __name__ == "__main__":
    main()
