name: Scheduled Data Pipeline

on:
  schedule:
    # Runs at 4:00 PM IST (10:30 UTC), after the Indian market closes.
    - cron: '30 10 * * *'
  workflow_dispatch: # This line allows you to manually run the workflow from the Actions tab on GitHub.

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Make sure this matches your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the data pipeline
      env: # Use this section to securely store API keys as GitHub Secrets
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        # You would also add ALPHA_VANTAGE_API_KEY if you were still using it
      run: python run_pipeline.py